@baseUrl = http://localhost:3000/api




### GET
GET {{baseUrl}}/entries




### POST /entries
POST {{baseUrl}}/entries
Content-Type: application/json

{
    "restaurant": "Cornelia Poletto",
    "address": "Eppendorfer Landstraße 80, 20249 Hamburg",
    "description": "Cornelia Polettos Gourmet-Küche im italienischen Gastronomia-Stil: Legeres Restaurant und exquisiter Feinkostladen in einem.",
    "url": "https://cornelia-poletto.de/",
    "categories": "Mediterranean", "Fine Dining"
}

### DELETE /entries
DELETE {{baseUrl}}/entries
Content-Type: application/json

{
"_id": "62559164bae29ca748de69cf"
}